version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db2
      POSTGRES_PASSWORD: 061kW5hngY
      POSTGRES_DB: db2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  prisma-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: "postgresql://db2:061kW5hngY@postgres:5432/db2?schema=db2"
      JWT_ACCESS_SECRET: SECRET123
      JWT_REFRESH_SECRET: ANOTHER_SECRET123

volumes:
  postgres-data:
  pgadmin-data:
